version: '3.1'
services:
  mariadb:
    container_name: "db"
    image: your-own-db
    ports:
      - "your-db-port"
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_USER: id
      MYSQL_PASSWORD: pw
      MYSQL_DATABASE: db
    restart: on-failure
  redis:
    container_name: "session_store"
    image: redis
    ports:
      - "6379:6379"
  server:
    depends_on:
      - your-own-db
      - redis
    container_name: "server"
    build: .
    ports:
      - "5000:5000"
    command: yarn fast-start
    environment:
      PORT: 5000
      DATABASE_NAME: db
      DATABASE_HOST: your-own-db
      DATABASE_ID: id
      DATABASE_PW: pw

      REDIS_HOST: redis
    restart: on-failure
    links:
      - redis
      - your-own-db